#!/usr/bin/env node
/**
 * cms-langs — emit every language-dependent artefact from one list of codes.
 *
 * `cms-check` and `cms-gen` cover the *data* layer (JSON ↔ Decap configs ↔
 * i18n.tsx). They say nothing about the pieces that also have to grow when a
 * language is added:
 *
 *   - `public/_redirects`  — root redirect + a `/<lang>/admin` pair per code
 *   - hreflang alternates  — one `<link>` per code, plus `x-default`
 *   - `src/pages/<lang>/`  — one route folder per code
 *
 * Those were hand-written for two languages in the source project, and neither
 * scales by itself: the hreflang block hardcodes `/(en|fr)/` in a regex, and the
 * redirects file lists each code literally. Adding `pt` by hand means touching
 * three unrelated files and is easy to half-do.
 *
 * This script derives all three from `LANGS` in cms-lib.mjs (itself checked
 * against i18n.tsx by cms-check, so there is a single source of truth).
 *
 * Usage:
 *   node scripts/cms-langs.mjs              # report what is missing
 *   node scripts/cms-langs.mjs --redirects  # print the _redirects block
 *   node scripts/cms-langs.mjs --hreflang   # print the <head> snippet
 *   node scripts/cms-langs.mjs --pages      # create missing src/pages/<lang>/
 */

import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { DEFAULT_LANG, LANGS, RTL_LANGS, abs } from "./cms-lib.mjs";

const args = new Set(process.argv.slice(2));
const ALL = args.size === 0;

// ---------------------------------------------------------------------------
// _redirects
// ---------------------------------------------------------------------------
function redirectsBlock() {
  const lines = [
    "# Root → default language",
    `/  /${DEFAULT_LANG}/  302`,
    "",
    "# Admin locale aliases — one pair per language so /<lang>/admin reaches the CMS.",
  ];
  for (const l of LANGS) {
    lines.push(`/${l}/admin    /admin/    301`);
    lines.push(`/${l}/admin/   /admin/    301`);
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// hreflang
//
// One alternate per language plus x-default (pointing at the default language),
// which search engines use for visitors whose language you do not publish.
//
// The path rewrite matches a whole segment and tries longer codes first, so
// region-suffixed codes (pt-BR alongside pt) are not truncated — the same bug
// class that affected detectInitialLang.
// ---------------------------------------------------------------------------
function hreflangSnippet() {
  const byLength = [...LANGS].sort((a, b) => b.length - a.length);
  const alt = byLength.join("|");
  const line = (code, target) =>
    `    <link rel="alternate" hreflang="${code}" href={new URL(Astro.url.pathname.replace(/^\\/(${alt})(?=\\/|$)/, "/${target}"), Astro.site ?? Astro.url).href} />`;

  return [
    "    {/* hreflang alternates — generated by scripts/cms-langs.mjs */}",
    ...LANGS.map((l) => line(l, l)),
    line("x-default", DEFAULT_LANG),
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Route folders
// ---------------------------------------------------------------------------
function pageFolders(create = false) {
  const rows = [];
  for (const l of LANGS) {
    const dir = `src/pages/${l}`;
    const exists = existsSync(abs(dir));
    if (!exists && create) mkdirSync(abs(dir), { recursive: true });
    rows.push({ dir, exists, created: !exists && create });
  }
  return rows;
}

// ---------------------------------------------------------------------------

if (ALL || args.has("--redirects")) {
  const path = "public/_redirects";
  const current = existsSync(abs(path)) ? readFileSync(abs(path), "utf8") : "";
  const missing = LANGS.filter((l) => !current.includes(`/${l}/admin`));
  if (args.has("--redirects")) {
    console.log(redirectsBlock());
  } else {
    console.log(
      missing.length
        ? `✗ ${path}: no /admin alias for ${missing.join(", ")} — run --redirects and merge the block`
        : `✓ ${path}: an /admin alias exists for every language`,
    );
    // Whitespace between columns is free-form in _redirects, so match on
    // structure rather than the exact spacing this script happens to emit.
    if (!/^\/\s+\/[\w-]+\/?\s+\d{3}/m.test(current)) {
      console.log(`  ! root redirect to /${DEFAULT_LANG}/ not found`);
    }
  }
}

if (ALL || args.has("--hreflang")) {
  if (args.has("--hreflang")) {
    console.log(hreflangSnippet());
  } else {
    // Best-effort: look for the layout the source project uses.
    const layout = "src/layouts/BaseLayout.astro";
    if (existsSync(abs(layout))) {
      const src = readFileSync(abs(layout), "utf8");
      const missing = LANGS.filter((l) => !src.includes(`hreflang="${l}"`));
      const hasDefault = src.includes('hreflang="x-default"');
      console.log(
        missing.length
          ? `✗ ${layout}: no hreflang for ${missing.join(", ")} — run --hreflang and paste into <head>`
          : `✓ ${layout}: an hreflang alternate exists for every language`,
      );
      if (!hasDefault) console.log(`  ! no hreflang="x-default" alternate`);
    } else {
      console.log(`? ${layout} not found — run --hreflang and paste the snippet into your layout's <head>`);
    }
  }
}

if (ALL || args.has("--pages")) {
  const rows = pageFolders(args.has("--pages"));
  for (const r of rows) {
    if (r.created) console.log(`+ ${r.dir} created`);
    else if (r.exists) console.log(`✓ ${r.dir}`);
    else console.log(`✗ ${r.dir} missing — run --pages to create it`);
  }
}

if (ALL) {
  const rtl = LANGS.filter((l) => RTL_LANGS.has(l));
  if (rtl.length) {
    console.log(
      `! ${rtl.join(", ")} are RTL: set dir="rtl" on <html> for those languages ` +
        `and audit Tailwind logical properties. Not automated.`,
    );
  }
  console.log(`\nlanguages: ${LANGS.join(", ")} (default: ${DEFAULT_LANG})`);
}
