// Generates Astro page wrappers for routes still rendered as a single React island.
//
// Behaviour:
// - Each generated file starts with the sentinel `AUTO_HEADER` below.
// - On run, if a target file does NOT start with that sentinel, it is treated as
//   hand-maintained and left untouched (safe: never clobbers manual edits).
// - Files that don't exist yet, or files that do start with the sentinel, are
//   (re)written from the templates.
//
// Hand-maintained pages (orchestrating multiple .astro components natively):
//   - src/pages/{fr,en}/index.astro
//   - src/pages/{fr,en}/about/index.astro
//   - src/pages/{fr,en}/about/history.astro
//   - src/pages/{fr,en}/about/values.astro
//   - src/pages/{fr,en}/about/join.astro
//   - src/pages/{fr,en}/blog/index.astro
//   - src/pages/{fr,en}/initiatives/index.astro
//   - src/pages/{fr,en}/resources/*.astro
//
// Anything in the lists below that has been hand-edited is preserved automatically
// thanks to the sentinel guard.

import fs from "node:fs";
import path from "node:path";

const root = path.resolve(process.cwd(), "src/pages");
const langs = ["fr", "en"];

const AUTO_HEADER = "{/* AUTO-GENERATED by scripts/generate-pages.mjs — edits are overwritten unless this header is removed */}";

// Static pages: [relativePath, importName, importPath, clientDirective?]
const staticPages = [
  ["contact.astro",                     "ContactForm",          "@/components/contact/ContactForm",        "client:load"],
  ["about/index.astro",                 "AboutPage",            "@/components/pages/About"],
  ["about/history.astro",               "HistoirePage",         "@/components/pages/Histoire"],
  ["about/values.astro",                "ValeursPage",          "@/components/pages/Valeurs"],
  ["about/join.astro",                  "AdhesionPage",         "@/components/pages/Adhesion"],
  ["blog/index.astro",                  "BlogPage",             "@/components/pages/Blog"],
  ["initiatives/index.astro",           "InitiativesPage",      "@/components/pages/Initiatives"],
  ["resources/publications.astro",      "ResourcesPublications","@/components/pages/ResourcesPublications"],
  ["resources/toolkits.astro",          "ResourcesToolkits",    "@/components/pages/ResourcesToolkits"],
  ["resources/media.astro",             "ResourcesMedia",       "@/components/pages/ResourcesMedia"],
];

const thematiqueRoutes = [
  ["initiatives/innovation.astro", "innovation"],
  ["initiatives/democracy.astro",  "democracy"],
  ["initiatives/engagement.astro", "engagement"],
  ["initiatives/media.astro",      "media"],
  ["initiatives/training.astro",   "training"],
];

function staticPage(lang, importName, importPath, directive = "client:only=\"react\"") {
  return `---
export const prerender = true;
import BaseLayout from "@/layouts/BaseLayout.astro";
import ${importName} from "${importPath}";
const lang = "${lang}";
---
${AUTO_HEADER}
<BaseLayout lang={lang}>
  <${importName} lang={lang} ${directive} />
</BaseLayout>
`;
}

function thematiquePage(lang, key) {
  return `---
export const prerender = true;
import BaseLayout from "@/layouts/BaseLayout.astro";
import ThematiquePage from "@/components/thematique/ThematiquePage";
import { thematiques } from "@/data/thematiques";
const lang = "${lang}";
const data = thematiques["${key}"];
---
${AUTO_HEADER}
<BaseLayout lang={lang} mainClass="">
  <ThematiquePage data={data} lang={lang} client:load />
</BaseLayout>
`;
}

function blogSlugPage(lang) {
  return `---
import BaseLayout from "@/layouts/BaseLayout.astro";
import BlogPost from "@/components/pages/BlogPost";
import { fetchPostBySlug } from "@/lib/wordpress";

const lang = "${lang}";
const { slug } = Astro.params;

let post = null;
try {
  post = await fetchPostBySlug(slug);
} catch (err) {
  console.error("[BlogPost SSR prefetch] failed:", err);
}

const preload = post ? [{ key: ["post", slug], data: post }] : [];
---
${AUTO_HEADER}
<BaseLayout lang={lang}>
  <script is:inline define:vars={{ slug, preload }}>
    window.__ASTRO_PARAMS__ = { slug };
    window.__PRELOAD__ = preload;
  </script>
  <BlogPost client:only="react" />
</BaseLayout>
`;
}

function projetSlugPage(lang) {
  return `---
import BaseLayout from "@/layouts/BaseLayout.astro";
import ProjetDetail from "@/components/pages/ProjetDetail";
import { fetchProjetBySlugWithLang } from "@/lib/wordpress";

const lang = "${lang}";
const { slug } = Astro.params;

let projet = null;
try {
  projet = await fetchProjetBySlugWithLang(slug, lang);
} catch (err) {
  console.error("[ProjetDetail SSR prefetch] failed:", err);
}

const preload = projet ? [{ key: ["projet", slug, lang], data: projet }] : [];
---
${AUTO_HEADER}
<BaseLayout lang={lang}>
  <script is:inline define:vars={{ slug, preload }}>
    window.__ASTRO_PARAMS__ = { slug };
    window.__PRELOAD__ = preload;
  </script>
  <ProjetDetail client:only="react" />
</BaseLayout>
`;
}

function notFoundPage(lang) {
  return `---
import BaseLayout from "@/layouts/BaseLayout.astro";
import NotFound from "@/components/pages/NotFound";
const lang = "${lang}";
Astro.response.status = 404;
---
${AUTO_HEADER}
<BaseLayout lang={lang}>
  <NotFound client:only="react" />
</BaseLayout>
`;
}

/** Write file iff it does not exist OR starts with the AUTO_HEADER sentinel. */
function safeWrite(filePath, content) {
  if (fs.existsSync(filePath)) {
    const existing = fs.readFileSync(filePath, "utf8");
    if (!existing.includes(AUTO_HEADER)) {
      console.log(`  skip (hand-maintained): ${path.relative(root, filePath)}`);
      return false;
    }
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log(`  wrote: ${path.relative(root, filePath)}`);
  return true;
}

let written = 0;
let skipped = 0;

for (const lang of langs) {
  for (const [rel, importName, importPath, directive] of staticPages) {
    const filePath = path.join(root, lang, rel);
    if (safeWrite(filePath, staticPage(lang, importName, importPath, directive))) written++;
    else skipped++;
  }
  for (const [rel, key] of thematiqueRoutes) {
    const filePath = path.join(root, lang, rel);
    if (safeWrite(filePath, thematiquePage(lang, key))) written++;
    else skipped++;
  }

  const blogSlug = path.join(root, lang, "blog/[slug].astro");
  if (safeWrite(blogSlug, blogSlugPage(lang))) written++; else skipped++;

  const projetSlug = path.join(root, lang, "initiatives/[slug].astro");
  if (safeWrite(projetSlug, projetSlugPage(lang))) written++; else skipped++;
}

// Global 404 (no language; defaults to fr)
const notFound = path.join(root, "404.astro");
if (safeWrite(notFound, notFoundPage("fr"))) written++; else skipped++;

console.log(`\nDone: ${written} written, ${skipped} skipped (hand-maintained).`);
